package bingen

import (
	"bytes"
	"encoding/binary"
	"testing"
)

func TestGenerateAppliesAssignedProfilesAndPatchOverrides(t *testing.T) {
	project := &Project{
		Settings: Settings{
			Profiles: []HardwareProfile{
				{ID: "base", AssignedIds: "1-2", LedCount: 60, LedType: 1, ColorOrder: 2, BrightnessCap: 120},
				{ID: "override", LedCount: 144, LedType: 4, ColorOrder: 5, BrightnessCap: 200},
			},
			Patch: map[string]string{"2": "override"},
		},
	}

	result, err := Generate(project)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	prop1 := readPropConfig(t, result.Bytes, 1)
	if prop1.LedCount != 60 || prop1.LedType != 1 || prop1.ColorOrder != 2 || prop1.BrightnessCap != 120 {
		t.Fatalf("unexpected prop1 config: %+v", prop1)
	}

	prop2 := readPropConfig(t, result.Bytes, 2)
	if prop2.LedCount != 144 || prop2.LedType != 4 || prop2.ColorOrder != 5 || prop2.BrightnessCap != 200 {
		t.Fatalf("unexpected prop2 config after patch override: %+v", prop2)
	}

	prop3 := readPropConfig(t, result.Bytes, 3)
	if prop3.LedCount != 164 || prop3.BrightnessCap != 255 {
		t.Fatalf("expected default config for prop3, got %+v", prop3)
	}
}

func TestGenerateAddsGapAndFinalOffEvents(t *testing.T) {
	project := &Project{
		Settings: Settings{
			ShowDuration: 5000,
		},
		PropGroups: []PropGroup{
			{ID: "g1", IDs: "1-2"},
		},
		Tracks: []Track{
			{
				Type:    "led",
				GroupId: "g1",
				Clips: []Clip{
					{StartTime: 1000, Duration: 1500, Type: "solid", Props: ClipProps{Color: "#FF0000"}},
				},
			},
		},
	}

	result, err := Generate(project)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	if result.EventCount != 3 {
		t.Fatalf("expected gap, clip, and final off events, got %d", result.EventCount)
	}
}

func TestGenerateAppendsCueBlockForEnabledCues(t *testing.T) {
	a := 1200
	c := 3400
	project := &Project{
		Settings: Settings{
			ShowDuration: 5000,
		},
		PropGroups: []PropGroup{
			{ID: "g1", IDs: "1"},
		},
		Tracks: []Track{
			{
				Type:    "led",
				GroupId: "g1",
				Clips: []Clip{
					{StartTime: 0, Duration: 1000, Type: "solid", Props: ClipProps{Color: "#112233"}},
				},
			},
		},
		Cues: []Cue{
			{ID: "A", TimeMs: &a, Enabled: true},
			{ID: "B", TimeMs: nil, Enabled: false},
			{ID: "C", TimeMs: &c, Enabled: true},
			{ID: "D", TimeMs: nil, Enabled: false},
		},
	}

	result, err := Generate(project)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	idx := bytes.Index(result.Bytes, []byte("CUE1"))
	if idx == -1 {
		t.Fatal("expected cue block magic in generated bytes")
	}

	version := binary.LittleEndian.Uint16(result.Bytes[idx+4 : idx+6])
	count := binary.LittleEndian.Uint16(result.Bytes[idx+6 : idx+8])
	cueA := binary.LittleEndian.Uint32(result.Bytes[idx+8 : idx+12])
	cueB := binary.LittleEndian.Uint32(result.Bytes[idx+12 : idx+16])
	cueC := binary.LittleEndian.Uint32(result.Bytes[idx+16 : idx+20])
	cueD := binary.LittleEndian.Uint32(result.Bytes[idx+20 : idx+24])

	if version != 1 {
		t.Fatalf("expected cue block version 1, got %d", version)
	}
	if count != 4 {
		t.Fatalf("expected cue block count 4, got %d", count)
	}
	if cueA != uint32(a) || cueC != uint32(c) {
		t.Fatalf("unexpected enabled cue times: A=%d C=%d", cueA, cueC)
	}
	if cueB != 0xFFFFFFFF || cueD != 0xFFFFFFFF {
		t.Fatalf("expected disabled cues to use sentinel value, got B=%d D=%d", cueB, cueD)
	}
}

func TestHelperFunctions(t *testing.T) {
	ids := parseIDRange("1, 3-4, bad, 0, 500, 9-7")
	if len(ids) != 3 || ids[0] != 1 || ids[1] != 3 || ids[2] != 4 {
		t.Fatalf("unexpected parsed ids: %v", ids)
	}

	mask := calculateMask("1,33,64")
	if mask[0] != 1 {
		t.Fatalf("expected bit 0 in first mask word, got %032b", mask[0])
	}
	if mask[1] != (uint32(1) | (uint32(1) << 31)) {
		t.Fatalf("unexpected second mask word: %032b", mask[1])
	}
	if isMaskEmpty(mask) {
		t.Fatal("expected populated mask to be non-empty")
	}
	if !isMaskEmpty([MaskArraySize]uint32{}) {
		t.Fatal("expected zero-value mask to be empty")
	}

	if parseColor("#FFAA00") != 0xFFAA00 {
		t.Fatalf("expected parseColor to decode #FFAA00")
	}
	if parseColor("not-a-color") != 0 {
		t.Fatalf("expected invalid colors to decode to 0")
	}
	if getEffectCode("sparkle") != 16 {
		t.Fatalf("expected sparkle effect code 16")
	}
	if getEffectCode("unknown") != 1 {
		t.Fatalf("expected unknown effect code to fall back to solid")
	}
}

func TestGenerateFromJSONRejectsInvalidJSON(t *testing.T) {
	if _, err := GenerateFromJSON(`{"settings":`); err == nil {
		t.Fatal("expected invalid JSON to return an error")
	}
}

func readPropConfig(t *testing.T, data []byte, propID int) PropConfig {
	t.Helper()

	const headerSize = 16
	const configSize = 8

	offset := headerSize + (propID-1)*configSize
	if len(data) < offset+configSize {
		t.Fatalf("generated binary too short for prop %d config", propID)
	}

	return PropConfig{
		LedCount:      binary.LittleEndian.Uint16(data[offset : offset+2]),
		LedType:       data[offset+2],
		ColorOrder:    data[offset+3],
		BrightnessCap: data[offset+4],
		Reserved:      [3]uint8{data[offset+5], data[offset+6], data[offset+7]},
	}
}
